[package]
name = "melee_server"
version = "0.1.0"
authors = ["Douglas Linsmeyer <douglinsmeyer@gmail.com> "]
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"