services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=mysql://user:password@db/meleedb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=meleedb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data: